global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
- job_name: 'api-gateway'
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: [ 'api-gateway:8080' ]

- job_name: 'product-service'
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: [ 'product-service:8081' ]

- job_name: 'order-service'
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: [ 'order-service:8083' ]

- job_name: 'payment-service'
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: [ 'payment-service:8082' ]

- job_name: 'customer-service'
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: [ 'customer-service:8084' ]

# Jika menggunakan Node Exporter untuk host metrics
- job_name: 'node-exporter'
  static_configs:
  - targets: [ 'node-exporter:9100' ]
