apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: | 
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'api-gateway'
        static_configs:
          - targets: ['api-gateway:8080']

      - job_name: 'product-service'
        static_configs:
          - targets: ['product-service:8081']

      - job_name: 'order-service'
        static_configs:
          - targets: ['order-service:8083']

      - job_name: 'payment-service'
        static_configs:
          - targets: ['payment-service:8082']

      - job_name: 'customer-service'
        static_configs:
          - targets: ['customer-service:8084']

      - job_name: 'node'
        static_configs:
          - targets: ['node-exporter:9100']
